<?php
/**
 * BackupResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpectrumVoip\\\\NetSapiens\Model;

use \ArrayAccess;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;

/**
 * BackupResponse Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BackupResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BackupResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'backup_hostname' => 'string',
        'backup_index' => 'int',
        'domain' => 'string',
        'type' => 'string',
        'backup_log_link' => 'string',
        'data_sync_results' => '\SpectrumVoip\\\\NetSapiens\Model\BackupResponseDataSyncResults',
        'database_backup_results' => '\SpectrumVoip\\\\NetSapiens\Model\BackupResponseDatabaseBackupResults'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'backup_hostname' => null,
        'backup_index' => null,
        'domain' => null,
        'type' => null,
        'backup_log_link' => null,
        'data_sync_results' => null,
        'database_backup_results' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'backup_hostname' => false,
        'backup_index' => false,
        'domain' => false,
        'type' => false,
        'backup_log_link' => false,
        'data_sync_results' => false,
        'database_backup_results' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'backup_hostname' => 'backup-hostname',
        'backup_index' => 'backup-index',
        'domain' => 'domain',
        'type' => 'type',
        'backup_log_link' => 'backup-log-link',
        'data_sync_results' => 'data-sync-results',
        'database_backup_results' => 'database-backup-results'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'backup_hostname' => 'setBackupHostname',
        'backup_index' => 'setBackupIndex',
        'domain' => 'setDomain',
        'type' => 'setType',
        'backup_log_link' => 'setBackupLogLink',
        'data_sync_results' => 'setDataSyncResults',
        'database_backup_results' => 'setDatabaseBackupResults'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'backup_hostname' => 'getBackupHostname',
        'backup_index' => 'getBackupIndex',
        'domain' => 'getDomain',
        'type' => 'getType',
        'backup_log_link' => 'getBackupLogLink',
        'data_sync_results' => 'getDataSyncResults',
        'database_backup_results' => 'getDatabaseBackupResults'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('backup_hostname', $data ?? [], null);
        $this->setIfExists('backup_index', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('backup_log_link', $data ?? [], null);
        $this->setIfExists('data_sync_results', $data ?? [], null);
        $this->setIfExists('database_backup_results', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['backup_hostname'] === null) {
            $invalidProperties[] = "'backup_hostname' can't be null";
        }
        if ($this->container['backup_index'] === null) {
            $invalidProperties[] = "'backup_index' can't be null";
        }
        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['backup_log_link'] === null) {
            $invalidProperties[] = "'backup_log_link' can't be null";
        }
        if ($this->container['data_sync_results'] === null) {
            $invalidProperties[] = "'data_sync_results' can't be null";
        }
        if ($this->container['database_backup_results'] === null) {
            $invalidProperties[] = "'database_backup_results' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets backup_hostname
     *
     * @return string
     */
    public function getBackupHostname()
    {
        return $this->container['backup_hostname'];
    }

    /**
     * Sets backup_hostname
     *
     * @param string $backup_hostname backup_hostname
     *
     * @return self
     */
    public function setBackupHostname($backup_hostname)
    {
        if (is_null($backup_hostname)) {
            throw new \InvalidArgumentException('non-nullable backup_hostname cannot be null');
        }
        $this->container['backup_hostname'] = $backup_hostname;

        return $this;
    }

    /**
     * Gets backup_index
     *
     * @return int
     */
    public function getBackupIndex()
    {
        return $this->container['backup_index'];
    }

    /**
     * Sets backup_index
     *
     * @param int $backup_index backup_index
     *
     * @return self
     */
    public function setBackupIndex($backup_index)
    {
        if (is_null($backup_index)) {
            throw new \InvalidArgumentException('non-nullable backup_index cannot be null');
        }
        $this->container['backup_index'] = $backup_index;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets backup_log_link
     *
     * @return string
     */
    public function getBackupLogLink()
    {
        return $this->container['backup_log_link'];
    }

    /**
     * Sets backup_log_link
     *
     * @param string $backup_log_link backup_log_link
     *
     * @return self
     */
    public function setBackupLogLink($backup_log_link)
    {
        if (is_null($backup_log_link)) {
            throw new \InvalidArgumentException('non-nullable backup_log_link cannot be null');
        }
        $this->container['backup_log_link'] = $backup_log_link;

        return $this;
    }

    /**
     * Gets data_sync_results
     *
     * @return \SpectrumVoip\\\\NetSapiens\Model\BackupResponseDataSyncResults
     */
    public function getDataSyncResults()
    {
        return $this->container['data_sync_results'];
    }

    /**
     * Sets data_sync_results
     *
     * @param \SpectrumVoip\\\\NetSapiens\Model\BackupResponseDataSyncResults $data_sync_results data_sync_results
     *
     * @return self
     */
    public function setDataSyncResults($data_sync_results)
    {
        if (is_null($data_sync_results)) {
            throw new \InvalidArgumentException('non-nullable data_sync_results cannot be null');
        }
        $this->container['data_sync_results'] = $data_sync_results;

        return $this;
    }

    /**
     * Gets database_backup_results
     *
     * @return \SpectrumVoip\\\\NetSapiens\Model\BackupResponseDatabaseBackupResults
     */
    public function getDatabaseBackupResults()
    {
        return $this->container['database_backup_results'];
    }

    /**
     * Sets database_backup_results
     *
     * @param \SpectrumVoip\\\\NetSapiens\Model\BackupResponseDatabaseBackupResults $database_backup_results database_backup_results
     *
     * @return self
     */
    public function setDatabaseBackupResults($database_backup_results)
    {
        if (is_null($database_backup_results)) {
            throw new \InvalidArgumentException('non-nullable database_backup_results cannot be null');
        }
        $this->container['database_backup_results'] = $database_backup_results;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


