<?php
/**
 * DomainsDomainTimeframesId2PostRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpectrumVoip\\\\NetSapiens\Model;

use \ArrayAccess;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;

/**
 * DomainsDomainTimeframesId2PostRequest Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DomainsDomainTimeframesId2PostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_domains__domain__timeframes__id__2_post_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'timeframe_specific_dates_array' => '\SpectrumVoip\\\\NetSapiens\Model\TimeframeSpecificDate[]',
        'timeframe_holiday_array' => '\SpectrumVoip\\\\NetSapiens\Model\TimeframeHoliday[]',
        'timeframe_days_of_week_array' => '\SpectrumVoip\\\\NetSapiens\Model\TimeframeDOW[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'timeframe_specific_dates_array' => null,
        'timeframe_holiday_array' => null,
        'timeframe_days_of_week_array' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'timeframe_specific_dates_array' => false,
        'timeframe_holiday_array' => false,
        'timeframe_days_of_week_array' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timeframe_specific_dates_array' => 'timeframe-specific-dates-array',
        'timeframe_holiday_array' => 'timeframe-holiday-array',
        'timeframe_days_of_week_array' => 'timeframe-days-of-week-array'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timeframe_specific_dates_array' => 'setTimeframeSpecificDatesArray',
        'timeframe_holiday_array' => 'setTimeframeHolidayArray',
        'timeframe_days_of_week_array' => 'setTimeframeDaysOfWeekArray'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timeframe_specific_dates_array' => 'getTimeframeSpecificDatesArray',
        'timeframe_holiday_array' => 'getTimeframeHolidayArray',
        'timeframe_days_of_week_array' => 'getTimeframeDaysOfWeekArray'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('timeframe_specific_dates_array', $data ?? [], null);
        $this->setIfExists('timeframe_holiday_array', $data ?? [], null);
        $this->setIfExists('timeframe_days_of_week_array', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timeframe_specific_dates_array
     *
     * @return \SpectrumVoip\\\\NetSapiens\Model\TimeframeSpecificDate[]|null
     */
    public function getTimeframeSpecificDatesArray()
    {
        return $this->container['timeframe_specific_dates_array'];
    }

    /**
     * Sets timeframe_specific_dates_array
     *
     * @param \SpectrumVoip\\\\NetSapiens\Model\TimeframeSpecificDate[]|null $timeframe_specific_dates_array timeframe_specific_dates_array
     *
     * @return self
     */
    public function setTimeframeSpecificDatesArray($timeframe_specific_dates_array)
    {
        if (is_null($timeframe_specific_dates_array)) {
            throw new \InvalidArgumentException('non-nullable timeframe_specific_dates_array cannot be null');
        }
        $this->container['timeframe_specific_dates_array'] = $timeframe_specific_dates_array;

        return $this;
    }

    /**
     * Gets timeframe_holiday_array
     *
     * @return \SpectrumVoip\\\\NetSapiens\Model\TimeframeHoliday[]|null
     */
    public function getTimeframeHolidayArray()
    {
        return $this->container['timeframe_holiday_array'];
    }

    /**
     * Sets timeframe_holiday_array
     *
     * @param \SpectrumVoip\\\\NetSapiens\Model\TimeframeHoliday[]|null $timeframe_holiday_array timeframe_holiday_array
     *
     * @return self
     */
    public function setTimeframeHolidayArray($timeframe_holiday_array)
    {
        if (is_null($timeframe_holiday_array)) {
            throw new \InvalidArgumentException('non-nullable timeframe_holiday_array cannot be null');
        }
        $this->container['timeframe_holiday_array'] = $timeframe_holiday_array;

        return $this;
    }

    /**
     * Gets timeframe_days_of_week_array
     *
     * @return \SpectrumVoip\\\\NetSapiens\Model\TimeframeDOW[]|null
     */
    public function getTimeframeDaysOfWeekArray()
    {
        return $this->container['timeframe_days_of_week_array'];
    }

    /**
     * Sets timeframe_days_of_week_array
     *
     * @param \SpectrumVoip\\\\NetSapiens\Model\TimeframeDOW[]|null $timeframe_days_of_week_array timeframe_days_of_week_array
     *
     * @return self
     */
    public function setTimeframeDaysOfWeekArray($timeframe_days_of_week_array)
    {
        if (is_null($timeframe_days_of_week_array)) {
            throw new \InvalidArgumentException('non-nullable timeframe_days_of_week_array cannot be null');
        }
        $this->container['timeframe_days_of_week_array'] = $timeframe_days_of_week_array;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


