<?php
/**
 * Synchronous
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpectrumVoip\\\\NetSapiens\Model;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;

/**
 * Synchronous Class Doc Comment
 *
 * @category Class
 * @description When synchronous is requested with \&quot;yes\&quot; the response will be a 200 on success and will contain a valid JSON representiation of the new resource. If no or left off request a 202 \&quot;Accepted\&quot; will be given in a success case and this can be considered a success. Synchronous responses will be a little slower as the API will process the geo replication request and wait till the local copy has been written and can be read back berfore sending a response.
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Synchronous
{
    /**
     * Possible values of this enum
     */
    public const YES = 'yes';

    public const NO = 'no';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::YES,
            self::NO
        ];
    }
}


