<?php
/**
 * CreateUserRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateUserRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateUserRequest
 * @package     SpectrumVoip\\\\NetSapiens
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateUserRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateUserRequest"
     */
    public function testCreateUserRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "synchronous"
     */
    public function testPropertySynchronous()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name_first_name"
     */
    public function testPropertyNameFirstName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name_last_name"
     */
    public function testPropertyNameLastName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "login_username"
     */
    public function testPropertyLoginUsername()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_scope"
     */
    public function testPropertyUserScope()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_login_pin"
     */
    public function testPropertyVoicemailLoginPin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "privacy"
     */
    public function testPropertyPrivacy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_plan"
     */
    public function testPropertyDialPlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_policy"
     */
    public function testPropertyDialPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status_message"
     */
    public function testPropertyStatusMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_presence_status"
     */
    public function testPropertyUserPresenceStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directory_name_number_dtmf_mapping"
     */
    public function testPropertyDirectoryNameNumberDtmfMapping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_user_control_enabled"
     */
    public function testPropertyVoicemailUserControlEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone_numbers_to_allow_enabled"
     */
    public function testPropertyPhoneNumbersToAllowEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone_numbers_to_reject_enabled"
     */
    public function testPropertyPhoneNumbersToRejectEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "call_screening_enabled"
     */
    public function testPropertyCallScreeningEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ring_no_answer_timeout_seconds"
     */
    public function testPropertyRingNoAnswerTimeoutSeconds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "language_token"
     */
    public function testPropertyLanguageToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "limits_max_data_storage_kilobytes"
     */
    public function testPropertyLimitsMaxDataStorageKilobytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "limits_max_active_calls_total"
     */
    public function testPropertyLimitsMaxActiveCallsTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directory_annouce_in_dial_by_name_enabled"
     */
    public function testPropertyDirectoryAnnouceInDialByNameEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directory_override_order_duplicate_dtmf_mapping"
     */
    public function testPropertyDirectoryOverrideOrderDuplicateDtmfMapping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_greeting_index"
     */
    public function testPropertyVoicemailGreetingIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_enabled"
     */
    public function testPropertyVoicemailEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_receive_broadcast_enabled"
     */
    public function testPropertyVoicemailReceiveBroadcastEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reject_anonymous_calls_enabled"
     */
    public function testPropertyRejectAnonymousCallsEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_playback_announce_datetime_received"
     */
    public function testPropertyVoicemailPlaybackAnnounceDatetimeReceived()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_playback_announce_caller_id"
     */
    public function testPropertyVoicemailPlaybackAnnounceCallerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_playback_sort_newest_to_oldest"
     */
    public function testPropertyVoicemailPlaybackSortNewestToOldest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_send_alert_new_voicemail_cc_list_csv"
     */
    public function testPropertyEmailSendAlertNewVoicemailCcListCsv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_send_alert_new_voicemail_behavior"
     */
    public function testPropertyEmailSendAlertNewVoicemailBehavior()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_send_alert_new_voicemail_enabled"
     */
    public function testPropertyEmailSendAlertNewVoicemailEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_send_alert_new_missed_call_enabled"
     */
    public function testPropertyEmailSendAlertNewMissedCallEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_send_alert_data_storage_limit_reached_enabled"
     */
    public function testPropertyEmailSendAlertDataStorageLimitReachedEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "caller_id_number"
     */
    public function testPropertyCallerIdNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "caller_id_name"
     */
    public function testPropertyCallerIdName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "caller_id_number_emergency"
     */
    public function testPropertyCallerIdNumberEmergency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "area_code"
     */
    public function testPropertyAreaCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directory_name_visible_in_list_enabled"
     */
    public function testPropertyDirectoryNameVisibleInListEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voicemail_transcription_enabled"
     */
    public function testPropertyVoicemailTranscriptionEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emergency_address_id"
     */
    public function testPropertyEmergencyAddressId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "call_recordings_hide_from_others_enabled"
     */
    public function testPropertyCallRecordingsHideFromOthersEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "music_on_hold_randomized_enabled"
     */
    public function testPropertyMusicOnHoldRandomizedEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "music_on_hold_comfort_message_repeat_interval_seconds"
     */
    public function testPropertyMusicOnHoldComfortMessageRepeatIntervalSeconds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "active_calls_total_current"
     */
    public function testPropertyActiveCallsTotalCurrent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recording_configuration"
     */
    public function testPropertyRecordingConfiguration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_status"
     */
    public function testPropertyAccountStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_datetime"
     */
    public function testPropertyCreatedDatetime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_modified_datetime"
     */
    public function testPropertyLastModifiedDatetime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
