<?php
/**
 * UpdateDialruleRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateDialruleRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateDialruleRequest
 * @package     SpectrumVoip\\\\NetSapiens
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateDialruleRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateDialruleRequest"
     */
    public function testUpdateDialruleRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dail_rule_matching_to_uri"
     */
    public function testPropertyDailRuleMatchingToUri()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dialrule"
     */
    public function testPropertyDialrule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dail_rule_matching_from_uri"
     */
    public function testPropertyDailRuleMatchingFromUri()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_matching_day_of_week"
     */
    public function testPropertyDialRuleMatchingDayOfWeek()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_matching_start_date"
     */
    public function testPropertyDialRuleMatchingStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_matching_end_date"
     */
    public function testPropertyDialRuleMatchingEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_matching_start_time"
     */
    public function testPropertyDialRuleMatchingStartTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_matching_end_time"
     */
    public function testPropertyDialRuleMatchingEndTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_application"
     */
    public function testPropertyDialRuleApplication()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_parameter"
     */
    public function testPropertyDialRuleParameter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_destination_scheme"
     */
    public function testPropertyDialRuleTranslationDestinationScheme()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_destination_user"
     */
    public function testPropertyDialRuleTranslationDestinationUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_destination_host"
     */
    public function testPropertyDialRuleTranslationDestinationHost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_source_name"
     */
    public function testPropertyDialRuleTranslationSourceName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_source_scheme"
     */
    public function testPropertyDialRuleTranslationSourceScheme()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_source_user"
     */
    public function testPropertyDialRuleTranslationSourceUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_translation_source_host"
     */
    public function testPropertyDialRuleTranslationSourceHost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dial_rule_description"
     */
    public function testPropertyDialRuleDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
