<?php
/**
 * ContactsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Api;

use \SpectrumVoip\\\\NetSapiens\Configuration;
use \SpectrumVoip\\\\NetSapiens\ApiException;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for domainsDomainUsersUserContactsContactIdDelete
     *
     * Delete Contact.
     *
     */
    public function testDomainsDomainUsersUserContactsContactIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserContactsContactIdGet
     *
     * Get Specific Contact for User.
     *
     */
    public function testDomainsDomainUsersUserContactsContactIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserContactsContactIdPut
     *
     * Update Contact.
     *
     */
    public function testDomainsDomainUsersUserContactsContactIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserContactsCountGet
     *
     * Count Contacts for User.
     *
     */
    public function testDomainsDomainUsersUserContactsCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserContactsGet
     *
     * Get Contacts for User.
     *
     */
    public function testDomainsDomainUsersUserContactsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserContactsPost
     *
     * Create Contact.
     *
     */
    public function testDomainsDomainUsersUserContactsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsUsersContactsGet
     *
     * Get My Contacts.
     *
     */
    public function testDomainsUsersContactsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
