<?php
/**
 * EventSubscriptionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Api;

use \SpectrumVoip\\\\NetSapiens\Configuration;
use \SpectrumVoip\\\\NetSapiens\ApiException;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EventSubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventSubscriptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSubscription
     *
     * Create a Event Subscription.
     *
     */
    public function testCreateSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSubscription
     *
     * Delete a subscription.
     *
     */
    public function testDeleteSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readSubscription
     *
     * Read Event Subscription By Id.
     *
     */
    public function testReadSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readSubscriptions
     *
     * Read Event Subscriptions.
     *
     */
    public function testReadSubscriptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSubscription
     *
     * Update an Event Subscription.
     *
     */
    public function testUpdateSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
