<?php
/**
 * MediaGreetingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Api;

use \SpectrumVoip\\\\NetSapiens\Configuration;
use \SpectrumVoip\\\\NetSapiens\ApiException;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediaGreetingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaGreetingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createGreetingBase64
     *
     * Create a new Greeting from Upload (JSON + Base64 File).
     *
     */
    public function testCreateGreetingBase64()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createGreetingFileUpload
     *
     * Create a new Greeting from Upload (Multipart/Mixed Post).
     *
     */
    public function testCreateGreetingFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createGreetingTTS
     *
     * Create a new Greeting from TTS.
     *
     */
    public function testCreateGreetingTTS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteGreeting
     *
     * Delete Specific Greeting for User.
     *
     */
    public function testDeleteGreeting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readGreeting
     *
     * Read Specific Greeting for User.
     *
     */
    public function testReadGreeting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readGreetings
     *
     * Read Greetings for User.
     *
     */
    public function testReadGreetings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGreetingBase64
     *
     * Update Greeting from Upload (JSON + Base64 File).
     *
     */
    public function testUpdateGreetingBase64()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGreetingFileUpload
     *
     * Update Greeting from Upload (Multipart/Mixed Post).
     *
     */
    public function testUpdateGreetingFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGreetingTTS
     *
     * Update Greeting with TTS script.
     *
     */
    public function testUpdateGreetingTTS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
