<?php
/**
 * MediaHoldMessagesUserApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetSapiens API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpectrumVoip\\\\NetSapiens\Test\Api;

use \SpectrumVoip\\\\NetSapiens\Configuration;
use \SpectrumVoip\\\\NetSapiens\ApiException;
use \SpectrumVoip\\\\NetSapiens\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediaHoldMessagesUserApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpectrumVoip\\\\NetSapiens
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaHoldMessagesUserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteMsgUser
     *
     * Delete Hold Messge for User.
     *
     */
    public function testDeleteMsgUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainsDomainUsersUserMsgPost
     *
     * Create a new Hold Messge for User from Upload (Multipart/Mixed Post).
     *
     */
    public function testDomainsDomainUsersUserMsgPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readMsgUser
     *
     * Read Hold Messages for User.
     *
     */
    public function testReadMsgUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMsgUserFileUpload
     *
     * Update Hold Messge for User from Upload (Multipart/Mixed Post).
     *
     */
    public function testUpdateMsgUserFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
